name: notus
description: Platform-agnostic rich text document model based on Delta format and used in Zefyr editor.
version: 1.0.0-rc.2
homepage: https://github.com/memspace/zefyr

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  collection: ^1.17.0
  coverage: ^1.6.3
  quill_delta: ^3.0.0-nullsafety.2
  quiver: ^3.2.1

dev_dependencies:
  test: ^1.24.2
  lints: ^2.0.1
