name: zefyr
description: Clean, minimalistic and collaboration-ready rich text editor for Flutter.
version: 1.0.0-rc.6
homepage: https://github.com/memspace/zefyr

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.17.1
  url_launcher: ^6.1.12
  quill_delta: ^3.0.0-nullsafety.2
  notus: ^1.0.0-rc.2
  characters: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2


dependency_overrides:
  notus:
    git:
      url: https://github.com/IVLIVS-III/zefyr.git
      path: packages/notus
